# Generated by Django 2.1.7 on 2019-03-15 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='account balance')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('CNY', 'CNY'), ('EUR', 'EUR')], max_length=5, verbose_name='account currency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='account owner')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='transaction amount')),
                ('source_currency', models.CharField(choices=[('USD', 'USD'), ('CNY', 'CNY'), ('EUR', 'EUR')], max_length=5, verbose_name='source currency')),
                ('destination_currency', models.CharField(choices=[('USD', 'USD'), ('CNY', 'CNY'), ('EUR', 'EUR')], max_length=5, verbose_name='source currency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='accounts.Account', verbose_name='destination account')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcoming_transactions', to='accounts.Account', verbose_name='source account')),
            ],
        ),
    ]
